name: linux
run-name: linux ${{ github.actor }}-{{ github.event.pull_request.number }}-${{ github.run_number }} 😸

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

  setup:
    needs: checkout
    uses: ./.github/workflows/linux-setup.yaml

  unit-tests:
    needs: setup
    uses: ./.github/workflows/unit_tests.yaml
    with:
      os: ubuntu-latest

  # code-coverage:
  #   runs-on: ubuntu-latest
  #   needs: unit-tests
  #   uses: ./.github/workflows/code_coverage.yaml