name: linux-setup
run-name: linux-setup ${{ github.actor }}-${{ github.event.pull_request.number }}-${{ github.run_number }} 😸

on:
  workflow_call:

jobs:
  setup-linux:
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Pretty print
        run: echo "Setting up an ubuntu-latest machine"
      
      



      # - name: Install GCC 13
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y software-properties-common
      #     sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      #     sudo apt-get update
      #     sudo apt-get install -y gcc-13 g++-13
      #     sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
      #     sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      # - name: checkout
      #   uses: actions/checkout@v4
      #   with:
      #     submodules: recursive

      # - name: Install Wired
      #   run: |
      #     mkdir build && cd build
      #     cmake ..
      #     sudo cmake --install .
