name: Setup

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  setup:
    uses: ./.github/workflows/setup-${{ inputs.os }}.yaml
    runs-on: ${{ inputs.os }}
