name: Setup

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: LS
        run: ls