name: Setup

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  setup-ubuntu:
    if: ${{ inputs.os == 'ubuntu-latest' }}
    uses: ./.github/workflows/setup-ubuntu-latest.yaml

  setup-windows:
    if: ${{ inputs.os == 'windows-latest' }}
    uses: ./.github/workflows/setup-windows-latest.yaml