name: unit-tests
run-name: unit-tests ${{ github.actor }}-{{ github.event.pull_request.number }}-${{ github.run_number }} 😸

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  unit-tests:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install library
        run: |
          mkdir build && cd build
          cmake ..
          sudo cmake --install .

      - name: Build tests
        run: |
          mkdir build && cd build
          cmake .. -DUNIT_TESTS=ON
          cmake --build . --parallel 

      - name: Run unit tests
        run: |
          cd build/tests/unit
          ./unit
          