name: Unit Tests
run-name: ${{ github.actor }} is running unit tests 😸

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install GCC 13
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Build tests
        run: |
          cd tests/unit
          mkdir build && cd build
          cmake ..
          cmake --build . --config release --parallel

      - name: Run unit tests
        run: |
          cd tests/unit/build
          ./unit_tests
          